
package com.soap.ws.client_jp;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.2
 * Generated source version: 2.2
 * 
 */
@WebService(name = "LibraryWSImpl", targetNamespace = "http://ws/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface LibraryWSImpl {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "searchPublicationByTopic", targetNamespace = "http://ws/", className = "com.soap.ws.client_jp.SearchPublicationByTopic")
    @ResponseWrapper(localName = "searchPublicationByTopicResponse", targetNamespace = "http://ws/", className = "com.soap.ws.client_jp.SearchPublicationByTopicResponse")
    @Action(input = "http://ws/LibraryWSImpl/searchPublicationByTopicRequest", output = "http://ws/LibraryWSImpl/searchPublicationByTopicResponse")
    public String searchPublicationByTopic(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

}
